Updated build workflow for stable

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,6 +31,7 @@ jobs:
           restore-keys: ${{ runner.os }}-msys2-
 
       - name: setup msys2 ucrt64
+        id: msys2
         uses: msys2/setup-msys2@v2
         with:
           msystem: UCRT64
@@ -46,27 +47,17 @@ jobs:
             mingw-w64-ucrt-x86_64-headers-git mingw-w64-ucrt-x86_64-jbigkit mingw-w64-ucrt-x86_64-libgccjit
             mingw-w64-ucrt-x86_64-libiconv mingw-w64-ucrt-x86_64-libidn2 mingw-w64-ucrt-x86_64-libjpeg-turbo
             mingw-w64-ucrt-x86_64-libpng mingw-w64-ucrt-x86_64-librsvg mingw-w64-ucrt-x86_64-libtree-sitter
-            mingw-w64-ucrt-x86_64-libtiff mingw-w64-ucrt-x86_64-libunistring mingw-w64-ucrt-x86_64-libxml2
-            mingw-w64-ucrt-x86_64-nettle mingw-w64-ucrt-x86_64-p11-kit mingw-w64-ucrt-x86_64-winpthreads
-            mingw-w64-ucrt-x86_64-xpm-nox mingw-w64-ucrt-x86_64-xz mingw-w64-ucrt-x86_64-zlib pkgconf texinfo zip
-
-      # - name: extract version from configure.ac
-      #   id: extract
-      #   run: |
-      #     export LC_ALL=C.UTF-8
-      #     VERSION=$(grep -oP 'AC_INIT\(\[GNU Emacs\],\s*\[\K[^]]+' configure.ac)
-      #     FF_VERSION="${VERSION}-b${GITHUB_RUN_NUMBER}"
-      #     echo "Extracted version: $FF_VERSION"
-      #     echo "version=$FF_VERSION" >> $GITHUB_OUTPUT
-
+            mingw-w64-ucrt-x86_64-libtiff mingw-w64-ucrt-x86_64-libunistring mingw-w64-ucrt-x86_64-nettle 
+            mingw-w64-ucrt-x86_64-p11-kit mingw-w64-ucrt-x86_64-winpthreads mingw-w64-ucrt-x86_64-xpm-nox 
+            mingw-w64-ucrt-x86_64-xz mingw-w64-ucrt-x86_64-zlib pkgconf texinfo zip mingw-w64-ucrt-x86_64-libxml2
       - name: extract version from configure.ac
         id: extract
         run: |
           export LC_ALL=C.UTF-8
           VERSION=$(grep -oP 'AC_INIT\(\[GNU Emacs\],\s*\[\K[^]]+' configure.ac)
-          echo "Extracted version: $VERSION"
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
-
+          FF_VERSION="${VERSION}-b1"
+          echo "Extracted version: $FF_VERSION"
+          echo "version=$FF_VERSION" >> $GITHUB_OUTPUT
       - name: build
         # build options tailored for windows
         run: |
@@ -82,7 +73,7 @@ jobs:
           export CXXFLAGS="$CFLAGS"
           export LDFLAGS="-Wl,--as-needed -Wl,--no-insert-timestamp"
           ../configure \
-            --prefix="${PWD}/../ffemacs" \
+            --prefix="${PWD}/../zipme/ffemacs" \
             --with-w32 \
             --with-native-compilation=aot \
             --with-tree-sitter \
@@ -101,25 +92,46 @@ jobs:
             --without-pop \
             --without-sound \
             --without-compress-install \
-            --without-imagemagick            
+            --without-imagemagick
           make -j$(nproc)
           make install
-          ls -ld ../ffemacs || echo "ERROR: ffemacs directory not found! make install may have failed silently"
-          if [ ! -d "../ffemacs" ]; then exit 1; fi
-
-      - name: copy in gcc dependencies
+          ls -ld ../zipme/ffemacs || echo "ERROR: ffemacs directory not found! make install may have failed silently"
+          if [ ! -d "../zipme/ffemacs" ]; then exit 1; fi
+      - name: copy in .dlls and gcc dependencies
         run: |
-          cp -r gcc ffemacs/lib/gcc
-
-      - name: package binaries
-        run: |
-          zip -r ffemacs.zip ffemacs
+          cp -r gcc zipme/ffemacs/lib/gcc
+          cp D:/a/_temp/msys64/ucrt64/bin/libbrotlicommon.dll zipme/ffemacs/bin/libbrotlicommon.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libbrotlidec.dll zipme/ffemacs/bin/libbrotlidec.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libbz2-1.dll zipme/ffemacs/bin/libbz2-1.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libfreetype-6.dll zipme/ffemacs/bin/libfreetype-6.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libgccjit-0.dll zipme/ffemacs/bin/libgccjit-0.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libgcc_s_seh-1.dll zipme/ffemacs/bin/libgcc_s_seh-1.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libglib-2.0-0.dll zipme/ffemacs/bin/libglib-2.0-0.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libgmp-10.dll zipme/ffemacs/bin/libgmp-10.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libgomp-1.dll zipme/ffemacs/bin/libgomp-1.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libgraphite2.dll zipme/ffemacs/bin/libgraphite2.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libharfbuzz-0.dll zipme/ffemacs/bin/libharfbuzz-0.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libiconv-2.dll zipme/ffemacs/bin/libiconv-2.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libintl-8.dll zipme/ffemacs/bin/libintl-8.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libisl-23.dll zipme/ffemacs/bin/libisl-23.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libmpc-3.dll zipme/ffemacs/bin/libmpc-3.dll 
+          cp D:/a/_temp/msys64/ucrt64/bin/libmpfr-6.dll zipme/ffemacs/bin/libmpfr-6.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libpcre2-8-0.dll zipme/ffemacs/bin/libpcre2-8-0.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libpng16-16.dll zipme/ffemacs/bin/libpng16-16.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libstdc++-6.dll zipme/ffemacs/bin/libstdc++-6.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libtree-sitter-0.25.dll zipme/ffemacs/bin/libtree-sitter-0.25.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libwinpthread-1.dll zipme/ffemacs/bin/libwinpthread-1.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libXpm-noX4.dll zipme/ffemacs/bin/libXpm-noX4.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/libzstd.dll zipme/ffemacs/bin/libzstd.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/wasmtime.dll zipme/ffemacs/bin/wasmtime.dll
+          cp D:/a/_temp/msys64/ucrt64/bin/zlib1.dll zipme/ffemacs/bin/zlib1.dll
+          
           
       - name: upload binaries as artifact
         uses: actions/upload-artifact@v4
         with:
-          name: ffemacs-${{ steps.extract.outputs.version }}-x86_64.zip
-          path: ffemacs.zip
+          name: ffemacs-${{ steps.extract.outputs.version }}-x86_64
+          path: zipme
           retention-days: 2
 
       - name: trigger target repo workflow
@@ -130,4 +142,4 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             https://api.github.com/repos/PAYLHORSE-Software/ffemacs/dispatches \
-            -d "{\"event_type\":\"receive_emacs_binaries\",\"client_payload\":{\"artifact_name\":\"ffemacs-${{ steps.extract.outputs.version }}-x86_64.zip\",\"source_repo\":\"${{ github.repository }}\",\"source_run_id\":\"${{ github.run_id }}\"}}"
+            -d "{\"event_type\":\"receive_emacs_binaries\",\"client_payload\":{\"artifact_name\":\"ffemacs-${{ steps.extract.outputs.version }}-x86_64\",\"source_repo\":\"${{ github.repository }}\",\"source_run_id\":\"${{ github.run_id }}\"}}"
